create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  address text not null,
  created_at timestamptz not null default now()
);

alter table public.deliveries enable row level security;

create policy "Anyone can submit a delivery"
  on public.deliveries for insert
  to anon
  with check (true);
